[build]
  base = "FE"
  command = "npm run build"
  publish = "dist/learn-english/browser"


[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

