[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --ignore-scripts"]

[phases.build]
cmds = ["export DATABASE_URL=postgresql://dummy:dummy@dummy:5432/dummy && npm run build"]

[start]
cmd = "node dist/main.js"
