[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --ignore-scripts"]

[phases.build]
cmds = ["npx prisma generate", "npx nest build"]

[start]
cmd = "node dist/main.js"
